### ISSUE TITLE
New blog posts are not updated

### ISSUE THREAD

**Issue by ccamara** [WarwickRUG/wrug_website#11]
New blog posts are not shown in listing + edits in default blog post are not updated here: https://warwickrug.github.io/wrug_website/posts/welcome/

**Comment by ccamara** [comment]
It well may be that prior to rendering the site, posts need to be knitted individually, every time there's a change. So the source code should contain the rmd file + html output (not very nice, actually)

**Comment by Selbosh** [comment]
> It well may be that prior to rendering the site, posts need to be knitted individually, every time there's a change. So the source code should contain the rmd file + html output (not very nice, actually)

Yes, this is how Distill works. The advantage of this approach is that older blog posts don't break if you update your R packages or dependencies and don't want to update the posts. If you don't fancy re-knitting every time then you can write an ordinary markdown post

**Comment by ccamara** [comment]
Thanks for the answer, @Selbosh ! I have never used distill before, so wasn't sure about this behaviour. It is not what I am used to do (I'm used to work with CI and I usually do not like manual processes that could be automated), but I can see its benefits. Also, not having to run r code for every single blog post speeds things up when rendering a site (which could have been problematic with old sites with plenty of content). I am still getting a bittersweet feeling with distill (as oposed to Hugo/blogdown), but this can be subject (and probably will) of a blog post and even a talk, as @jamestripp suggested ;)

@all-contributors please add @Selbosh for answering questions!

**Comment by ccamara** [comment]
Hehehe, I was testing how well the bot works with natural language processing (I'm testing many new things here ;) ) and I'm afraid it processes too much info.

**Comment by ccamara** [comment]
@all-contributors please add @Selbosh for answering questions.

**Comment by ccamara** [comment]
@all-contributors please add @Selbosh for answering questions.

**Comment by ccamara** [comment]
Added instructions in readme file.
